# Site settings
title: James Wu
email: you@example.com
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl: /projects # the subpath of your site, e.g. /blog/
url: /projects # the base hostname & protocol for your site
# twitter_username: twitter_username
#github_username:  jwjimmy
repository: jwjimmy/projects

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

# Modals
lightbox_path: "/lightbox/"

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/

gems: [jekyll-paginate, mini_magick, github-pages, thumbnails]

